### PR TITLE
Add new file mapping tool

### PR DESCRIPTION
**Pull request by marktriggs**
Adds a new set of mapping tools for dealing with files.  Just one so far, used by the KDL mapping.

### CODE REVIEW

**Comment by markbreedlove** [comment]
Looks good! The only thing I'd suggest is a quick spec test, even though `#extension_to_mimetype` is very simple.

**Comment by anarchivist** [comment]
:+1: agreed with @markbreedlove.

**Comment by marktriggs** [comment]
Thanks!  Tests added, and I've squashed the commits.

**Comment by anarchivist** [comment]
:+1:

**Pull request merged**
