### PR TITLE
Change the default query for CDL to exclude datasets

### PR DESCRIPTION
**Pull request by moltude**

### CODE REVIEW

**Comment by moltude** [comment]
I'm fixing the spec failures ...

**Comment by moltude** [comment]
:squash and ready for review

**Comment by anarchivist** [comment]
What's the motivation behind this change?

**Comment by no-reply** [comment]
Discussed in Slack from https://dpla.slack.com/archives/tech/p1467918252000281

@moltude if you make/find an appropriate redmine ticket documenting some of this more permanently, and link here, I'm happy to :merge:

**Comment by moltude** [comment]
@tom I've created a ticket for this item https://issues.dp.la/issues/8489

**Pull request merged**
