### PR TITLE
Add JSON logging and retries to NARAHarvester

### PR DESCRIPTION
**Pull request by no-reply**
NARA's API sometimes intermittently returns invalid JSON data. Because
the HTTP request succeeds, any retry mechanism through the HTTP client
misses these cases.

This adds an explicit catch for `JSON::ParserError`, with a 5 retry
regime. If the batch continually fails, we log the error and move to the
next batch.

Note that the failing requests are not single record requests, but
entire batches. See `Heidrun::IDSource#batches`.

### CODE REVIEW

**Comment by markbreedlove** [comment]
Looks good. My only question is how the JSON might be parseable only seconds after the previous try. Wouldn't it take a while for the issue to be resolved on the provider end?

**Comment by no-reply** [comment]
> My only question is how the JSON might be parseable only seconds after the previous try. Wouldn't it take a while for the issue to be resolved on the provider end?

We still don't have a clear indication of what is going on in the NARA API that's causing this, but it appears to be an intermittent problem with a very short lifetime--maybe even isolated to a single request.

i.e. it's not bad data, but a bug causing bad output. I've included a handful of retries, because this bug appears at a specific time, which suggests it may be tied to some scheduled server task; it's not clear how long that task might take.

**Comment by markbreedlove** [comment]
OK, thanks.  Would it be easy enough to add a brief comment to that effect?  I'll merge it then.

**Comment by no-reply** [comment]
Can do.

**Comment by no-reply** [comment]
comment added, squashed & force pushed. :merge: :question:

**Comment by markbreedlove** [comment]
Hi, @no-reply, it looks like the tests have failed.

**Comment by no-reply** [comment]
Looks like travis is just having build errors today. Not the first I've seen. I restarted the builds.

**Comment by no-reply** [comment]
1/2 that time. Stubbornly restarting the build again.

**Pull request merged**
