### PR TITLE
First sketch of NYPL harvester

### PR DESCRIPTION
**Pull request by marktriggs**
Happy Thanksgiving!  Ignore this until the festivities are over :)

This NYPL harvester isn't done yet (I haven't committed the tests, and I've only lightly tested by hand), but I wanted to get some eyes on it sooner rather than later because I'm not sure the direction is right.

I thought I should extend the API harvester for this, because NYPL's API is certainly that, and (unlike the Primo harvester), I felt like this harvester was contributor-specific and therefore seemed out of place with the other harvesters in KriKri.

In doing so, I can't help but notice that I've replaced almost every method from the API harvester class.  There's just not much commonality between NARA/MDL APIs and the NYPL one, so the inheritance isn't buying me much.  I've also had to change some of the method parameters:

  * in API harvester `next_options` takes a record count and works out the offset for the next page.  NYPL doesn't work like this--the API does the pagination for us, so its `next_options` needs to extract that pagination information from the response instead.

  * the API harvester `request` method assumes that you're always fetching the base `uri` and just varying the parameters.  NYPL requires fetching different URLs at different times, so I had to extend it to accept the URI to request.

So what I'm interested in discussing:

  * Should I be extending the API harvester at all?

  * If so, would we extend it to cover the slightly different NYPL cases?  I'd worry that it might become generic to the point of not really being useful.

  * If not, should the API harvester really be called SolrJsonHarvester?

Thanks!

Mark

### CODE REVIEW

**Comment by markbreedlove** [comment]
Hi, @marktriggs: I've been a little sidetracked from looking at this, but should get to it tomorrow morning.

**Comment by markbreedlove** [comment]
Hello, @marktriggs, and thanks!

Based on what you've said, I would vote not to extend the API harvester, and to create a new harvester class.

In the old system, the NYPL harvester used to extend an "AbsoluteURLHarvester." I don't think that was the best name, but it was designed to hit one URL that contains a list of sets ("collections"), and follow the links in that "root" URL response to get results for each set.  I think the implication of "Absolute" is that you can just hit those URLs in whatever order you like, because one does not depend upon the other -- that is, there's no resumption token or offset, and you're not submitting a query to select the records.

It may be helpful to note that there were three harvesters in the old system that extended AbsoluteURLHarvester:  NYPL, University of Virginia, and Internet Archive.  If you make a new base class that better suits the case at hand, you will get some code re-use in at least three harvesters.

I agree that the ApiHarvester should be renamed. There are many ways in which a legitimate web API could function that do not employ the same sort of looping and record counting as the prescribed one.  "SolrJSONHarvester" is probably a good name.

Another thing that I'd add is that the NYPL harvester, in the old system, was the one that we were able to multithread. This was made possible by its "absolute URL fetcher" nature, for lack of a better term. We could fetch multiple sets in parallel, and this was essential in NYPL's case, because we found that doing them single-threaded was taking something like an entire week.  (So beware of that.) It's probably time to think about multithreaded behavior in our harvesters now.

I'll let others weigh in ...  (Assigning to Mark M first)

**Comment by marktriggs** [comment]
Thanks @markbreedlove, I agree with all of that.

In the notes from @anarchivist, it was suggested that we might need to allow multiple harvest activities to run in parallel, so I had that in mind.  Right now, there's no multithreading, but you can pass a regex to limit which collections the harvester will grab.  For NYPL, the collection IDs are UUIDs, so you could (for example) split the harvest into two activities, with the first taking `/^[0-7]/` and the second taking `/^[8-9a-f]/`.

But this only works for collection IDs that can be sensibly matched with a regular expression, and would break down if one collection was very large compared to the others.  A cleverer threaded solution could get us around that (at the cost of having one activity running multiple threads, but maybe that's OK?)

**Comment by anarchivist** [comment]
Hm. Yeah, I suppose it's now time to talk about multithreading for harvesters... :rocket: I'll tag @no-reply here, too.

Anyhow, I believe that renaming the existing `ApiHarvester` is probably appropriate. MDL's harvester is using an API backed by a Solr index (although they just released a new version of the API that uses the [JSON API spec](http://jsonapi.org/)). CDL has a [similar Solr-based API](https://registry.cdlib.org/documentation/docs/technical-docs/solr-api/) from which we might be harvesting as well.

**Comment by marktriggs** [comment]
This harvester is replaced by the multi-threaded PR currently under review, so I'm closing this one out.

**Pull request closed without merging**
